### ISSUE TITLE
When this is going to be released as finished?

### ISSUE THREAD

**Issue by DaniGP17** [thorium-cfx/mono_v2_get_started#31]
Hello, I have been testing v2 of mono and it is impressive, I would love to use it for scripts because of its clear improvements compared to the previous version, I want to make scripts using v2 but I am not sure if the version will be finished, what is needed to finish the v2? Maybe I would be interested in collaborating to advance the development of v2.
Thank you so much

**Comment by Sasino97** [comment]
I'm not fully sure but this project seems to have been abandoned or hopefully paused

**Comment by thorium-cfx** [comment]
Sorry for the late reply.

As you may know we've recently been acquired by R*, ever since I've gotten more pressing matters that I need to attend to.

That said, this project is still our goal on moving forward with C#, it's actually awaiting a big rework that allows for more convenient (de)serialization, think: event listening type construction and sending of classes.

As of the ETA, it's unknown right now, but it's something I'll push forward again once the pressing matters are taken care of.

**Comment by DaniGP17** [comment]
Thank you very much for the answer
